server:
  port: 8082
  
spring:
  data:
    mongodb:
      database: RestaurantApp
      uri: mongodb+srv://root:root@tweetapp.v00ihzx.mongodb.net/RestaurantApp
#  sleuth:
#    sampler:
#      probability: 1.0 #Spring-Boot-2

eureka:
   client:
      serviceUrl:
         defaultZone: https://raes-prod.up.railway.app/eureka
      instance:
        preferIpAddress: true

user:
  auth:
    URL: https://ra-us-prod.up.railway.app/
    
management:
  tracing:
    sampling:
      probability: 1.0
      
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]' 
